import baseActionCreator from "./baseActionCreator";
import {
  LEFTCLICK,
  NEWBOARD,
  RESETWINLOSS,
  REVERTBOARD,
  RIGHTCLICK,
  TESTBOARD,
  UPDATEORIGINALBOARD,
  leftClick,
  newBoardAction,
  resetWinLoss,
  revertBoard,
  rightClick,
  testBoard,
  updateOriginalBoard
} from "./clickActionCreators";

import {
  DECREMENTMINESDISPLAY,
  DIFFICULTY,
  INCREMENTMINESDISPLAY,
  INCREMENTTIME,
  PAUSE,
  RESETTIME,
  SETLENGTH,
  SETMINES,
  SETMINESDISPLAY,
  SETWIDTH,
  decrementMinesDisplay,
  incrementMinesDisplay,
  incrementTime,
  pause,
  resetTime,
  setDifficulty,
  setLength,
  setMines,
  setMinesDisplay,
  setWidth
} from './formActionCreators'

import {
  setStats,
  setUsername,
  setBestBeginnerScore,
  setBestIntermediateScore,
  setBestExpertScore,
  setBeginnerScores,
  setIntermediateScores,
  setExpertScores,
  setTotalGamesCompleted,
  SETBESTBEGINNERSCORE,
  SETBESTINTERMEDIATESCORE,
  SETBESTEXPERTSCORE,
  SETBEGINNERSCORES,
  SETINTERMEDIATESCORES,
  SETEXPERTSCORES,
  SETTOTALGAMESCOMPLETED,
  SETUSERNAME,
  SETSTATS,
 } from "./statsActionCreators";

export {
  DECREMENTMINESDISPLAY,
  DIFFICULTY,
  INCREMENTMINESDISPLAY,
  INCREMENTTIME,
  LEFTCLICK,
  NEWBOARD,
  PAUSE,
  RESETTIME,
  RESETWINLOSS,
  REVERTBOARD,
  RIGHTCLICK,
  SETBEGINNERSCORES,
  SETBESTBEGINNERSCORE,
  SETBESTEXPERTSCORE,
  SETBESTINTERMEDIATESCORE,
  SETEXPERTSCORES,
  SETINTERMEDIATESCORES,
  SETLENGTH,
  SETMINES,
  SETMINESDISPLAY,
  SETSTATS,
  SETTOTALGAMESCOMPLETED,
  SETUSERNAME,
  SETWIDTH,
  TESTBOARD,
  UPDATEORIGINALBOARD,
  baseActionCreator,
  decrementMinesDisplay,
  incrementMinesDisplay,
  incrementTime,
  leftClick,
  newBoardAction,
  pause,
  resetTime,
  resetWinLoss,
  revertBoard,
  rightClick,
  setBeginnerScores,
  setBestBeginnerScore,
  setBestExpertScore,
  setBestIntermediateScore,
  setDifficulty,
  setExpertScores,
  setIntermediateScores,
  setLength,
  setMines,
  setMinesDisplay,
  setStats,
  setTotalGamesCompleted,
  setUsername,
  setWidth,
  testBoard,
  updateOriginalBoard,
 };
